version: "3.8"

services:
  task-manager-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydbname
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydbname" ]
      interval: 3s
      timeout: 3s
      retries: 5
  task-manager-database-service:
    build: ./TaskManagerDatabase
    depends_on:
      task-manager-database:
          condition: service_healthy
    volumes:
      - ./logs:/app/logs
  task-manager-api-service:
    build: ./TaskManagerAPI
    ports:
      - "80:8081"
    depends_on:
      task-manager-database:
        condition: service_healthy